SELECT d.`Age at enrollment` ,
	   d.`Application order` ,
	   d.`Curricular units 1st sem (credited)` as `1st sem (credited)`,
	   d.`Curricular units 1st sem (enrolled)` as `1st sem (enrolled)`,
	   d.`Curricular units 1st sem (evaluations)` as `1st sem (evaluations)`,
	   d.`Curricular units 1st sem (approved)` as `1st sem (approved)`,
	   d.`Curricular units 1st sem (grade)` as `1st sem (grade)`,
	   d.`Curricular units 1st sem (without evaluations)` as `1st sem (without evaluations)`,
	   d.`Curricular units 2nd sem (credited)`  as `2nd sem (credited)`,
	   d.`Curricular units 2nd sem (enrolled)` as `2nd sem (enrolled)`,
	   d.`Curricular units 2nd sem (evaluations)` as `2nd sem (evaluations)`,
	   d.`Curricular units 2nd sem (approved)` as `2nd sem (approved)`,
	   d.`Curricular units 2nd sem (grade)` as `2nd sem (grade)`,
	   d.`Curricular units 2nd sem (without evaluations)` as `2nd sem (without evaluations)`,
	   d.`Unemployment rate` ,
	   d.`Inflation rate` ,
	   d.GDP ,
	   d.Target, 
CASE WHEN d.`Marital status` = 1 THEN 'Single'
	 WHEN d.`Marital status` = 2 THEN 'Married'
	 WHEN d.`Marital status` = 3 THEN 'Widower'
	 WHEN d.`Marital status` = 4 THEN 'Divorced'
	 WHEN d.`Marital status` = 5 THEN 'Facto union'
	 WHEN d.`Marital status` = 6 THEN 'Legally separated'
END as `Marital status`,
CASE WHEN d.Gender = 1 THEN 'Male'
	 WHEN d.Gender = 0 THEN 'Female'
END as Gender,
CASE WHEN d.`Daytime/evening attendance` = 1 THEN 'Daytime'
	 WHEN d.`Daytime/evening attendance` = 0 THEN 'Evening'
END as `Daytime/evening attendance`,
CASE WHEN d.Displaced = 1 THEN 'Yes'
	 WHEN d.Displaced = 0 THEN 'No'
END as Displaced,
CASE WHEN d.`Educational special needs` = 1 THEN 'Yes'
	 WHEN d.`Educational special needs` = 0 THEN 'No'
END as `Educational special needs`,
CASE WHEN d.Debtor = 1 THEN 'Yes'
	 WHEN d.Debtor = 0 THEN 'No'
END as Debtor,
CASE WHEN d.`Tuition fees up to date` = 1 THEN 'Yes'
	 WHEN d.`Tuition fees up to date` = 0 THEN 'No'
END as `Tuition fees up to date`,
CASE WHEN d.`Scholarship holder` = 1 THEN 'Yes'
	 WHEN d.`Scholarship holder` = 0 THEN 'No'
END as `Scholarship holder`,
CASE WHEN d.International = 1 THEN 'Yes'
	 WHEN d.International = 0 THEN 'No'
END as International,
CASE WHEN d.`Application mode` = 1 THEN '1st phase—general contingent'
	 WHEN d.`Application mode` = 2 THEN 'Ordinance No. 612/93'
	 WHEN d.`Application mode` = 3 THEN '1st phase—special contingent (Azores Island)'
	 WHEN d.`Application mode` = 4 THEN 'Holders of other higher courses'
	 WHEN d.`Application mode` = 5 THEN 'Ordinance No. 854-B/99'
	 WHEN d.`Application mode` = 6 THEN 'International student (bachelor)'
	 WHEN d.`Application mode` = 7 THEN '1st phase—special contingent (Madeira Island)'
	 WHEN d.`Application mode` = 8 THEN '2nd phase—general contingent'
	 WHEN d.`Application mode` = 9 THEN '3rd phase—general contingent'
	 WHEN d.`Application mode` = 10 THEN 'Ordinance No. 533-A/99, item b2) (Different Plan)'
	 WHEN d.`Application mode` = 11 THEN 'Ordinance No. 533-A/99, item b3 (Other Institution)'
	 WHEN d.`Application mode` = 12 THEN 'Over 23 years old'
	 WHEN d.`Application mode` = 13 THEN 'Transfer'
	 WHEN d.`Application mode` = 14 THEN 'Change in course'
	 WHEN d.`Application mode` = 15 THEN 'Technological specialization diploma holders'
	 WHEN d.`Application mode` = 16 THEN 'Change in institution/course'
	 WHEN d.`Application mode` = 17 THEN 'Short cycle diploma holders'
	 WHEN d.`Application mode` = 18 THEN 'Change in institution/course (International)'
END as `Application mode`,
CASE WHEN d.Nacionality = 1 THEN 'Portuguese'
	 WHEN d.Nacionality = 2 THEN 'German'
	 WHEN d.Nacionality = 3 THEN 'Spanish'
	 WHEN d.Nacionality = 4 THEN 'Italian'
	 WHEN d.Nacionality = 5 THEN 'Dutch'
	 WHEN d.Nacionality = 6 THEN 'English'
	 WHEN d.Nacionality = 7 THEN 'Lithuanian'
	 WHEN d.Nacionality = 8 THEN 'Angolan'
	 WHEN d.Nacionality = 9 THEN 'Cape Verdean'
	 WHEN d.Nacionality = 10 THEN 'Guinean'
	 WHEN d.Nacionality = 11 THEN 'Mozambican'
	 WHEN d.Nacionality = 12 THEN 'Santomean'
	 WHEN d.Nacionality = 13 THEN 'Turkish'
	 WHEN d.Nacionality = 14 THEN 'Brazilian'
	 WHEN d.Nacionality = 15 THEN 'Romanian'
	 WHEN d.Nacionality = 16 THEN 'Moldova (Republic of)'
	 WHEN d.Nacionality = 17 THEN 'Mexican'
	 WHEN d.Nacionality = 18 THEN 'Ukrainian'
	 WHEN d.Nacionality = 19 THEN 'Russian'
	 WHEN d.Nacionality = 20 THEN 'Cuban'
	 WHEN d.Nacionality = 21 THEN 'Colombian'
END as Nationality,
CASE WHEN d.Course  = 1 THEN 'Biofuel Production Technologies'
	 WHEN d.Course  = 2 THEN 'Animation and Multimedia Design'
	 WHEN d.Course  = 3 THEN 'Social Service (evening attendance)'
	 WHEN d.Course  = 4 THEN 'Agronomy'
	 WHEN d.Course  = 5 THEN 'Communication Design'
	 WHEN d.Course  = 6 THEN 'Veterinary Nursing'
	 WHEN d.Course  = 7 THEN 'Informatics Engineering'
	 WHEN d.Course  = 8 THEN 'Equiniculture'
	 WHEN d.Course  = 9 THEN 'Management'
	 WHEN d.Course  = 10 THEN 'Social Service'
	 WHEN d.Course  = 11 THEN 'Tourism'
	 WHEN d.Course  = 12 THEN 'Nursing'
	 WHEN d.Course  = 13 THEN 'Oral Hygiene'
	 WHEN d.Course  = 14 THEN 'Advertising and Marketing Management'
	 WHEN d.Course  = 15 THEN 'Journalism and Communication'
	 WHEN d.Course  = 16 THEN 'Basic Education'
	 WHEN d.Course  = 17 THEN 'Management (evening attendance)'
END as Course,
CASE WHEN d.`Previous qualification` = 1 THEN 'Secondary education'
	 WHEN d.`Previous qualification` = 2 THEN 'Higher education—bachelor’s degree'
	 WHEN d.`Previous qualification` = 3 THEN 'Higher education—degree'
	 WHEN d.`Previous qualification` = 4 THEN 'Higher education—master’s degree'
	 WHEN d.`Previous qualification` = 5 THEN 'Higher education—doctorate'
	 WHEN d.`Previous qualification` = 6 THEN 'Frequency of higher education'
	 WHEN d.`Previous qualification` = 7 THEN '12th year of schooling—not completed'
	 WHEN d.`Previous qualification` = 8 THEN '11th year of schooling—not completed'
	 WHEN d.`Previous qualification` = 9 THEN 'Other—11th year of schooling'
	 WHEN d.`Previous qualification` = 10 THEN '10th year of schooling'
	 WHEN d.`Previous qualification` = 11 THEN '10th year of schooling—not completed'
	 WHEN d.`Previous qualification` = 12 THEN 'Basic education 3rd cycle (9th/10th/11th year) or equivalent'
	 WHEN d.`Previous qualification` = 13 THEN 'Basic education 2nd cycle (6th/7th/8th year) or equivalent'
	 WHEN d.`Previous qualification` = 14 THEN 'Technological specialization course'
	 WHEN d.`Previous qualification` = 15 THEN 'Higher education—degree (1st cycle)'
	 WHEN d.`Previous qualification` = 16 THEN 'Professional higher technical course'
	 WHEN d.`Previous qualification` = 17 THEN 'Higher education—master’s degree (2nd cycle)'
END as `Previous qualification`,
CASE WHEN d.`Mother's qualification` = 1 THEN 'Secondary Education—12th Year of Schooling or Equivalent'
	 WHEN d.`Mother's qualification` = 2 THEN 'Higher Education—bachelor’s degree'
	 WHEN d.`Mother's qualification` = 3 THEN 'Higher Education—degree'
	 WHEN d.`Mother's qualification` = 4 THEN 'Higher Education—master’s degree'
	 WHEN d.`Mother's qualification` = 5 THEN 'Higher Education—doctorate'
	 WHEN d.`Mother's qualification` = 6 THEN 'Frequency of Higher Education'
	 WHEN d.`Mother's qualification` = 7 THEN '12th Year of Schooling—not completed'
	 WHEN d.`Mother's qualification` = 8 THEN '11th Year of Schooling—not completed'
	 WHEN d.`Mother's qualification` = 9 THEN '7th Year (Old)'
	 WHEN d.`Mother's qualification` = 10 THEN 'Other—11th Year of Schooling'
	 WHEN d.`Mother's qualification` = 11 THEN '2nd year complementary high school course'
	 WHEN d.`Mother's qualification` = 12 THEN '10th Year of Schooling'
	 WHEN d.`Mother's qualification` = 13 THEN 'General commerce course'
	 WHEN d.`Mother's qualification` = 14 THEN 'Basic Education 3rd Cycle (9th/10th/11th Year) or Equivalent'
	 WHEN d.`Mother's qualification` = 15 THEN 'Complementary High School Course'
	 WHEN d.`Mother's qualification` = 16 THEN 'Technical-professional course'
	 WHEN d.`Mother's qualification` = 17 THEN 'Complementary High School Course—not concluded'
	 WHEN d.`Mother's qualification` = 18 THEN '7th year of schooling'
	 WHEN d.`Mother's qualification` = 19 THEN '2nd cycle of the general high school course'
	 WHEN d.`Mother's qualification` = 20 THEN '9th Year of Schooling—not completed'
	 WHEN d.`Mother's qualification` = 21 THEN '8th year of schooling'
	 WHEN d.`Mother's qualification` = 22 THEN 'General Course of Administration and Commerce'
	 WHEN d.`Mother's qualification` = 23 THEN 'Supplementary Accounting and Administration'
	 WHEN d.`Mother's qualification` = 24 THEN 'Unknown'
	 WHEN d.`Mother's qualification` = 25 THEN 'Cannot read or write'
	 WHEN d.`Mother's qualification` = 26 THEN 'Can read without having a 4th year of schooling'
	 WHEN d.`Mother's qualification` = 27 THEN 'Basic education 1st cycle (4th/5th year) or equivalent'
	 WHEN d.`Mother's qualification` = 28 THEN 'Basic Education 2nd Cycle (6th/7th/8th Year) or equivalent'
	 WHEN d.`Mother's qualification` = 29 THEN 'Technological specialization course'
	 WHEN d.`Mother's qualification` = 30 THEN 'Higher education—degree (1st cycle)'
	 WHEN d.`Mother's qualification` = 31 THEN 'Specialized higher studies course'
	 WHEN d.`Mother's qualification` = 32 THEN 'Professional higher technical course'
	 WHEN d.`Mother's qualification` = 33 THEN 'Higher Education—master’s degree (2nd cycle)'
	 WHEN d.`Mother's qualification` = 34 THEN 'Higher Education—doctorate (3rd cycle)'
END as `Mother's qualification`,
CASE WHEN d.`Father's qualification` = 1 THEN 'Secondary Education—12th Year of Schooling or Equivalent'
	 WHEN d.`Father's qualification` = 2 THEN 'Higher Education—bachelor’s degree'
	 WHEN d.`Father's qualification` = 3 THEN 'Higher Education—degree'
	 WHEN d.`Father's qualification` = 4 THEN 'Higher Education—master’s degree'
	 WHEN d.`Father's qualification` = 5 THEN 'Higher Education—doctorate'
	 WHEN d.`Father's qualification` = 6 THEN 'Frequency of Higher Education'
	 WHEN d.`Father's qualification` = 7 THEN '12th Year of Schooling—not completed'
	 WHEN d.`Father's qualification` = 8 THEN '11th Year of Schooling—not completed'
	 WHEN d.`Father's qualification` = 9 THEN '7th Year (Old)'
	 WHEN d.`Father's qualification` = 10 THEN 'Other—11th Year of Schooling'
	 WHEN d.`Father's qualification` = 11 THEN '2nd year complementary high school course'
	 WHEN d.`Father's qualification` = 12 THEN '10th Year of Schooling'
	 WHEN d.`Father's qualification` = 13 THEN 'General commerce course'
	 WHEN d.`Father's qualification` = 14 THEN 'Basic Education 3rd Cycle (9th/10th/11th Year) or Equivalent'
	 WHEN d.`Father's qualification` = 15 THEN 'Complementary High School Course'
	 WHEN d.`Father's qualification` = 16 THEN 'Technical-professional course'
	 WHEN d.`Father's qualification` = 17 THEN 'Complementary High School Course—not concluded'
	 WHEN d.`Father's qualification` = 18 THEN '7th year of schooling'
	 WHEN d.`Father's qualification` = 19 THEN '2nd cycle of the general high school course'
	 WHEN d.`Father's qualification` = 20 THEN '9th Year of Schooling—not completed'
	 WHEN d.`Father's qualification` = 21 THEN '8th year of schooling'
	 WHEN d.`Father's qualification` = 22 THEN 'General Course of Administration and Commerce'
	 WHEN d.`Father's qualification` = 23 THEN 'Supplementary Accounting and Administration'
	 WHEN d.`Father's qualification` = 24 THEN 'Unknown'
	 WHEN d.`Father's qualification` = 25 THEN 'Cannot read or write'
	 WHEN d.`Father's qualification` = 26 THEN 'Can read without having a 4th year of schooling'
	 WHEN d.`Father's qualification` = 27 THEN 'Basic education 1st cycle (4th/5th year) or equivalent'
	 WHEN d.`Father's qualification` = 28 THEN 'Basic Education 2nd Cycle (6th/7th/8th Year) or equivalent'
	 WHEN d.`Father's qualification` = 29 THEN 'Technological specialization course'
	 WHEN d.`Father's qualification` = 30 THEN 'Higher education—degree (1st cycle)'
	 WHEN d.`Father's qualification` = 31 THEN 'Specialized higher studies course'
	 WHEN d.`Father's qualification` = 32 THEN 'Professional higher technical course'
	 WHEN d.`Father's qualification` = 33 THEN 'Higher Education—master’s degree (2nd cycle)'
	 WHEN d.`Father's qualification` = 34 THEN 'Higher Education—doctorate (3rd cycle)'
END as `Father's qualification`,
CASE WHEN d.`Mother's occupation` = 1 THEN 'Student'
	 WHEN d.`Mother's occupation` = 2 THEN 'Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers'
	 WHEN d.`Mother's occupation` = 3 THEN 'Specialists in Intellectual and Scientific Activities'
	 WHEN d.`Mother's occupation` = 4 THEN 'Intermediate Level Technicians and Professions'
	 WHEN d.`Mother's occupation` = 5 THEN 'Administrative staff'
	 WHEN d.`Mother's occupation` = 6 THEN 'Personal Services, Security and Safety Workers, and Sellers'
	 WHEN d.`Mother's occupation` = 7 THEN 'Farmers and Skilled Workers in Agriculture, Fisheries, and Forestry'
	 WHEN d.`Mother's occupation` = 8 THEN 'Skilled Workers in Industry, Construction, and Craftsmen'
	 WHEN d.`Mother's occupation` = 9 THEN 'Installation and Machine Operators and Assembly Workers'
	 WHEN d.`Mother's occupation` = 10 THEN 'Unskilled Workers'
	 WHEN d.`Mother's occupation` = 11 THEN 'Armed Forces Professions'
	 WHEN d.`Mother's occupation` = 12 THEN 'Other Situation'
	 WHEN d.`Mother's occupation` = 13 THEN 'Unknow'
	 WHEN d.`Mother's occupation` = 14 THEN 'Armed Forces Officers'
	 WHEN d.`Mother's occupation` = 15 THEN 'Armed Forces Sergeants'
	 WHEN d.`Mother's occupation` = 16 THEN 'Other Armed Forces personnel'
	 WHEN d.`Mother's occupation` = 17 THEN 'Directors of administrative and commercial services'
	 WHEN d.`Mother's occupation` = 18 THEN 'Hotel, catering, trade, and other services directors'
	 WHEN d.`Mother's occupation` = 19 THEN 'Specialists in the physical sciences, mathematics, engineering,and related techniques'
	 WHEN d.`Mother's occupation` = 20 THEN 'Health professionals'
	 WHEN d.`Mother's occupation` = 21 THEN 'Teachers'
	 WHEN d.`Mother's occupation` = 22 THEN 'Specialists in finance, accounting, administrative organization, and public and commercial relations'
	 WHEN d.`Mother's occupation` = 23 THEN 'Intermediate level science and engineering technicians and professions'
	 WHEN d.`Mother's occupation` = 24 THEN 'Technicians and professionals of intermediate level of health'
	 WHEN d.`Mother's occupation` = 25 THEN 'Intermediate level technicians from legal, social, sports, cultural, and similar services'
	 WHEN d.`Mother's occupation` = 26 THEN 'Information and communication technology technicians'
	 WHEN d.`Mother's occupation` = 27 THEN 'Office workers, secretaries in general, and data processing operators'
	 WHEN d.`Mother's occupation` = 28 THEN 'Data, accounting, statistical, financial services, and registry-related operators'
	 WHEN d.`Mother's occupation` = 29 THEN 'Other administrative support staff'
	 WHEN d.`Mother's occupation` = 30 THEN 'Personal service workers'
	 WHEN d.`Mother's occupation` = 31 THEN 'Sellers'
	 WHEN d.`Mother's occupation` = 32 THEN 'Personal care workers and the like'
	 WHEN d.`Mother's occupation` = 33 THEN 'Protection and security services personnel'
	 WHEN d.`Mother's occupation` = 34 THEN 'Market-oriented farmers and skilled agricultural and animal production workers'
	 WHEN d.`Mother's occupation` = 35 THEN 'Farmers, livestock keepers, fishermen, hunters and gatherers, and subsistence'
	 WHEN d.`Mother's occupation` = 36 THEN 'Skilled construction workers and the like, except electricians'
	 WHEN d.`Mother's occupation` = 37 THEN 'Skilled workers in metallurgy, metalworking, and similar'
	 WHEN d.`Mother's occupation` = 38 THEN 'Skilled workers in electricity and electronics'
	 WHEN d.`Mother's occupation` = 39 THEN 'Workers in food processing, woodworking, and clothing and other industries and craftss'
	 WHEN d.`Mother's occupation` = 40 THEN 'Fixed plant and machine operators'
	 WHEN d.`Mother's occupation` = 41 THEN 'Assembly workers'
	 WHEN d.`Mother's occupation` = 42 THEN 'Vehicle drivers and mobile equipment operators'
	 WHEN d.`Mother's occupation` = 43 THEN 'Unskilled workers in agriculture, animal production, and fisheries and forestry'
	 WHEN d.`Mother's occupation` = 44 THEN 'Unskilled workers in extractive industry, construction, manufacturing, and transport'
	 WHEN d.`Mother's occupation` = 45 THEN 'Meal preparation assistants'
	 WHEN d.`Mother's occupation` = 46 THEN 'Street vendors (except food) and street service providers'
END as `Mother's occupation`,
CASE WHEN d.`Father's occupation` = 1 THEN 'Student'
	 WHEN d.`Father's occupation` = 2 THEN 'Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers'
	 WHEN d.`Father's occupation` = 3 THEN 'Specialists in Intellectual and Scientific Activities'
	 WHEN d.`Father's occupation` = 4 THEN 'Intermediate Level Technicians and Professions'
	 WHEN d.`Father's occupation` = 5 THEN 'Administrative staff'
	 WHEN d.`Father's occupation` = 6 THEN 'Personal Services, Security and Safety Workers, and Sellers'
	 WHEN d.`Father's occupation` = 7 THEN 'Farmers and Skilled Workers in Agriculture, Fisheries, and Forestry'
	 WHEN d.`Father's occupation` = 8 THEN 'Skilled Workers in Industry, Construction, and Craftsmen'
	 WHEN d.`Father's occupation` = 9 THEN 'Installation and Machine Operators and Assembly Workers'
	 WHEN d.`Father's occupation` = 10 THEN 'Unskilled Workers'
	 WHEN d.`Father's occupation` = 11 THEN 'Armed Forces Professions'
	 WHEN d.`Father's occupation` = 12 THEN 'Other Situation'
	 WHEN d.`Father's occupation` = 13 THEN 'Unknow'
	 WHEN d.`Father's occupation` = 14 THEN 'Armed Forces Officers'
	 WHEN d.`Father's occupation` = 15 THEN 'Armed Forces Sergeants'
	 WHEN d.`Father's occupation` = 16 THEN 'Other Armed Forces personnel'
	 WHEN d.`Father's occupation` = 17 THEN 'Directors of administrative and commercial services'
	 WHEN d.`Father's occupation` = 18 THEN 'Hotel, catering, trade, and other services directors'
	 WHEN d.`Father's occupation` = 19 THEN 'Specialists in the physical sciences, mathematics, engineering,and related techniques'
	 WHEN d.`Father's occupation` = 20 THEN 'Health professionals'
	 WHEN d.`Father's occupation` = 21 THEN 'Teachers'
	 WHEN d.`Father's occupation` = 22 THEN 'Specialists in finance, accounting, administrative organization, and public and commercial relations'
	 WHEN d.`Father's occupation` = 23 THEN 'Intermediate level science and engineering technicians and professions'
	 WHEN d.`Father's occupation` = 24 THEN 'Technicians and professionals of intermediate level of health'
	 WHEN d.`Father's occupation` = 25 THEN 'Intermediate level technicians from legal, social, sports, cultural, and similar services'
	 WHEN d.`Father's occupation` = 26 THEN 'Information and communication technology technicians'
	 WHEN d.`Father's occupation` = 27 THEN 'Office workers, secretaries in general, and data processing operators'
	 WHEN d.`Father's occupation` = 28 THEN 'Data, accounting, statistical, financial services, and registry-related operators'
	 WHEN d.`Father's occupation` = 29 THEN 'Other administrative support staff'
	 WHEN d.`Father's occupation` = 30 THEN 'Personal service workers'
	 WHEN d.`Father's occupation` = 31 THEN 'Sellers'
	 WHEN d.`Father's occupation` = 32 THEN 'Personal care workers and the like'
	 WHEN d.`Father's occupation` = 33 THEN 'Protection and security services personnel'
	 WHEN d.`Father's occupation` = 34 THEN 'Market-oriented farmers and skilled agricultural and animal production workers'
	 WHEN d.`Father's occupation` = 35 THEN 'Farmers, livestock keepers, fishermen, hunters and gatherers, and subsistence'
	 WHEN d.`Father's occupation` = 36 THEN 'Skilled construction workers and the like, except electricians'
	 WHEN d.`Father's occupation` = 37 THEN 'Skilled workers in metallurgy, metalworking, and similar'
	 WHEN d.`Father's occupation` = 38 THEN 'Skilled workers in electricity and electronics'
	 WHEN d.`Father's occupation` = 39 THEN 'Workers in food processing, woodworking, and clothing and other industries and craftss'
	 WHEN d.`Father's occupation` = 40 THEN 'Fixed plant and machine operators'
	 WHEN d.`Father's occupation` = 41 THEN 'Assembly workers'
	 WHEN d.`Father's occupation` = 42 THEN 'Vehicle drivers and mobile equipment operators'
	 WHEN d.`Father's occupation` = 43 THEN 'Unskilled workers in agriculture, animal production, and fisheries and forestry'
	 WHEN d.`Father's occupation` = 44 THEN 'Unskilled workers in extractive industry, construction, manufacturing, and transport'
	 WHEN d.`Father's occupation` = 45 THEN 'Meal preparation assistants'
	 WHEN d.`Father's occupation` = 46 THEN 'Street vendors (except food) and street service providers'
END as `Father's ocupation`
FROM dataset_python_preprocessing as d
 